require 'cxxproject/buildingblocks/binary_library'
require 'cxxproject/buildingblocks/building_block'
require 'cxxproject/buildingblocks/executable'
require 'cxxproject/buildingblocks/static_library'
require 'cxxproject/buildingblocks/module'
require 'cxxproject/buildingblocks/custom_building_block'
