# Just the default file wich is auto-required in the gem and which requires all needed stuff
require 'rubygems'
require 'yaml'
require 'rake/clean'
require 'cxxproject/utils'
require 'cxxproject/dependencies'
require 'cxxproject/configuration'
require 'cxxproject/buildingblock'
require 'cxxproject/torake'
require 'cxxproject/torake/compiler'
require 'cxxproject/torake/gcccompiler'
require 'cxxproject/torake/osxcompiler'
